services:
  customers:
    image: customers
    build:
      context: dar-msa-customers
      dockerfile: ../backend.Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bank
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: development
      APPLICATION_PORT: 80
    ports:
      - "8081:80"

  core:
    image: core
    build:
      context: dar-msa-core
      dockerfile: ../backend.Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bank
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: development
      APPLICATION_PORT: 80
      CUSTOMERS_API_BASE_URL: http://customers:80
    ports:
      - "8080:80"

  db:
    image: postgres:14-alpine3.20
    environment:
      POSTGRES_DB: bank
      POSTGRES_PASSWORD: 123
    ports:
      - "5431:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.4.2-alpine3.21
    ports:
      - "6379:6379"
