services:
  customers:
    build: ./dar-msa-customers
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bank
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: development
      APPLICATION_PORT: 80
    ports:
      - "8081:80"

  core:
    build: ./dar-msa-core
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bank
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: development
      APPLICATION_PORT: 80
      CUSTOMERS_API_BASE_URL: http://customers:80
    ports:
      - "8080:80"

  db:
    image: postgres:14-alpine3.20
    environment:
      POSTGRES_DB: bank
      POSTGRES_PASSWORD: 123
    ports:
      - "5431:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Todo: add redis