logging.level:
  org.springframework.data.r2dbc: DEBUG

spring:
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
