server:
  port: 8081

logging.level:
  org.springframework.data.r2dbc: DEBUG

spring:
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  expiration: 86400000 # 1 day
