server:
  port: ${APPLICATION_PORT}

spring:
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  expiration: 86400000 # 1 day
