server:
  port: ${APPLICATION_PORT}

spring:
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

api:
  customers:
    base-url: ${CUSTOMERS_API_BASE_URL}/api/customers
