server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  data:
    redis:
      host: localhost
      port: 6379


api:
  customers:
    base-url: http://localhost:8081/api/customers
